### ISSUE TITLE
onSubmit is never called

### ISSUE THREAD

**Issue by aashikagupta** [prestigegodson/pin-entry-text-field#3]
The onSubmit method is never called. The pin array gets clear before onSubmit is called in code. Thus, alert dialog(as given in example) is never shown.

Solution: call onSubmit before clearing the _pin array and text controllers.

**Comment by hjbdev** [comment]
Fixed in #4

**Comment by abolajibisiriyu** [comment]
This issue still persists.

**Comment by Ahmadre** [comment]
Fixed in this PR: https://github.com/prestigegodson/pin-entry-text-field/pull/11
