### ISSUE TITLE
Submit on last digit doesn't work

### ISSUE THREAD

**Issue by wolfcro1984** [prestigegodson/pin-entry-text-field#7]
When you type the last digit the onSubmit isn't invoked because of the error:
W/FlutterTextInput(17572): Unsupported operation: Cannot clear a fixed-length list

This is because you try to invoke
`_pin.clear() `
in the clearTextFields method and dart doesn't allow it.
I replaced it with
`_pin.forEach((e) => e = "");`
and now it works alright.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.14393], locale hr-HR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.26.1)
[√] VS Code, 64-bit edition (version 1.30.2)
[√] Connected device (1 available)

**Comment by chifuyu-toman** [comment]
Thanks, it solved my problem, I think you could do a pull request to fix this bug

**Comment by khadersaleem** [comment]
Yes this is the perfect solution. Please update the library.

**Comment by Ahmadre** [comment]
just fixed that. Follow this PR: https://github.com/prestigegodson/pin-entry-text-field/pull/11
