### ISSUE TITLE
Issue on More than 4 digit

### ISSUE THREAD

**Issue by firdarinoa** [prestigegodson/pin-entry-text-field#9]
Is it possible to make field more than 4? I have an error when do field: 6

**Comment by Ahmadre** [comment]
post your error please! I am doing a PR here and would like to sum up all bugs: https://github.com/prestigegodson/pin-entry-text-field/pull/11

**Comment by Ahmadre** [comment]
Ok just tested my PR on your use case. It works now with this PR: https://github.com/prestigegodson/pin-entry-text-field/pull/11
